Work for https://github.com/gbif/rs.gbif.org/issues/138

diff --git a/matching-ws/Dockerfile b/matching-ws/Dockerfile
--- a/matching-ws/Dockerfile
+++ b/matching-ws/Dockerfile
@@ -9,16 +9,32 @@ ARG CLB_URL=""
 ARG CLB_USER=""
 ARG CLB_PASSWORD=""
 ENV CLB_API_URL="https://api.checklistbank.org"
-ENV BACKEND_BRANCH="matching-ws"
+ARG GIT_BRANCH=""
+
+# Local builds - run from root of backend
+COPY .. /app/backend
+WORKDIR /app/backend
+
+# Run a script to validate the arguments
+#RUN if [ -z "$GIT_BRANCH" ]; then \
+#        echo "Error: GIT_BRANCH is not set." >&2; \
+#        exit 1; \
+#    fi
 
 # Clone the backend repository
-RUN rm -Rf backend
-RUN git clone https://github.com/CatalogueOfLife/backend.git
-WORKDIR /app/backend
-RUN git checkout $BACKEND_BRANCH
+#RUN rm -Rf backend
+#RUN git clone https://github.com/CatalogueOfLife/backend.git
+#WORKDIR /app/backend
+#RUN git checkout $GIT_BRANCH
 
 # Build all the CLB modules
 RUN mvn clean install package -DskipTests
+
+# Build the Maven project and create a exec file
+WORKDIR /app/backend/matching-ws
+
+# Run tests - full backend tests require additional services (e.g. ES)
+RUN mvn clean install package
 
 # Store git commit id and log
 RUN curl -o /app/backend/git.json -H "Accept: application/vnd.github+json" "https://api.github.com/repos/catalogueoflife/backend/commits/$(git rev-parse HEAD)"
@@ -37,12 +53,6 @@ RUN if [ -n "$CLB_DATASET_ID" ]; then \
     else \
         echo "{}" > /app/backend/dataset.json; \
     fi
-
-# Build the Maven project and create a exec file
-WORKDIR /app/backend/matching-ws
-
-# Run tests - full backend tests require additional services (e.g. ES)
-RUN mvn verify
 
 # Copy the executable JAR file from the builder image to the new image
 FROM openjdk:11
